site_name: Personal Documentation
theme:
  name: material 
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - toc:
      permalink: true

nav:
  - Home: index.md
  - Python:
    - Virtual environments:
              - About page: python/virtual_environments/about.md
              - Virtualenv : python/virtual_environments/virtualenv.md
              - Anaconda : python/virtual_environments/anaconda.md