site_name: Personal Documentation
theme:
  name: material
  features:
    - navigation.path  
    - content.code.copy
    - content.code.select
  palette: 
    - scheme: default
      primary: yellow
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/harrysharma1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/harry-sharma-567b21225/
    - icon: fontawesome/solid/paper-plane
      link: mailto:harrysharma1066@gmail.com
      
nav:
  - Home: index.md
  - Python:
    - About page: python/about.md
    - Virtual environments:
              - About page: python/virtual_environments/about.md
              - Virtualenv : python/virtual_environments/virtualenv.md
              - Anaconda : python/virtual_environments/anaconda.md