name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  lint_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check markdown
        run:  docker run -v $PWD:/code pipelinecomponents/markdownlint --style exclude.rb docs README.md 
  
  deploy:
    needs: lint_check
    runs-on: ubuntu-latest
    if: ${{ !needs.lint_check.outputs.lint.success }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy -b live --force
